version: '3.7'
services:
  db_gamification:
    image: mysql
    container_name: gamification_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamifi
      MYSQL_USER: gamification_user
      MYSQL_PASSWORD: gamification_secret
    ports:
      - "3308:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
